### ISSUE TITLE
Error: RNSmileId.captureSelfie got 3 arguments, expected 4

### ISSUE THREAD

**Issue by mateo2181** [smileidentity/SID_React_Sample#3]
Hi everyone,
I'm running with this issue following this depo app with the SDK when run: 
```
const data = await RnSmileId.captureSelfie("");
```

Does anyone have an idea about what can be the problem?

Working with:
```
"react-native": "0.60.4",
"rn-smile-id": "0.0.25"
```

Thanks!

**Comment by JNdhlovu** [comment]
const data = await RnSmileId.captureSelfie("",{}); will fix this issue with version 0.0.25 (note the empty object) however this has been rectified in version 0.0.26 and there should be no need to do this
